name: Aula da T16B
on: 
  push

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World t16b
        run: echo "Hello World"

      - name: Verifica o repositório do Git
        uses: actions/checkout@v3

      - name: Instalando o node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Instalar as dependências
        run: npm install

      - name: Executando o linter
        run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "t16b-prd"
          heroku_email: "andre.soares@betrybe.com"
          usedocker: true

